name = "c856-api"
compatibility_date = "2025-06-26"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]

# External dependencies for Wrangler v4
external = ["jose"]

[[d1_databases]]
binding = "DB"
database_name = "c856-database"
database_id = "a59a6c0e-cc34-4c29-b287-a7fac886ed82"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
GATSBY_FRONTEND_URL = "https://c856-prototype.pages.dev"